version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ski_db
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data: